---
- name: Initialize Docker Swarm on the first manager
  hosts: managers[0]
  become: true
  tasks:
    - name: Initialize Docker Swarm
      docker_swarm:
        state: present
        advertise_addr: enp0s8:2377
      register: swarm_init_output

- name: Join other managers to the Swarm
  hosts: managers[1:]
  become: true
  tasks:
    - name: Join Docker Swarm as Manager
      docker_swarm:
        state: join
        timeout: 60
        advertise_addr: enp0s8:2377
        join_token: "{{ hostvars[groups['managers'][0]]['swarm_init_output']['swarm_facts']['JoinTokens']['Manager'] }}"
        remote_addrs: "{{ groups['managers'][0] }}"
      when: "'{{ groups['managers'][0] }}' != inventory_hostname"

- name: Join the worker node to the Swarm
  hosts: workers
  become: true
  tasks:
    - name: Join Docker Swarm as Worker
      docker_swarm:
        state: join
        timeout: 60
        advertise_addr: enp0s8:2377
        join_token: "{{ hostvars[groups['managers'][0]]['swarm_init_output']['swarm_facts']['JoinTokens']['Worker'] }}"
        remote_addrs: "{{ groups['managers'][0] }}"

